[features]
seeds = false
skip-lint = false
[programs.localnet]
solarps = "ysvnEMvdfPVU7fAYr4yXUd3UyDq1ZWYRzrkNBHzt21r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/ubuntu/accounts/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
